
#############################################
#           makefile for prog3              #
#############################################
cordance: words.o listadt.o trees.o cordance.o
	em2 words.o listadt.o trees.o cordance.o -o cordance
