SUBRNAME CSECT
         STM   14,12,12(13)   STASH AWAY REGISTERS
         BALR  12,0           ESTABLISH IMPLIED BASE REGISTER
         USING *,12
         ST    13,SAV$AREA+4  STASH MAP TO TREASURE AND...
         LA    14,SAV$AREA    LINK SAVE AREAS
         ST    14,8(13)
         LR    13,14          POINT GPR13 AT LOCAL SAVE AREA
*
*
         LA    1,PARMADDR     GPR1 <- A(PARM ADDR LIST)
         L     15,=V(SUBR2)       GPR15 <- V(LOWER LEVEL SUBROUTINE)
         BALR  14,15          CALL SUBROUTINE; GPR14 <- RETURN ADDR
*
*
DONE     L     13,SAV$AREA+4  RESTORE MAP TO TREASURE
         L     14,12(13)      RESTORE RETURN ADDRESS
         L     15,RTN$CODE    SET RETURN CODE
         LM    0,12,20(13)    RESTORE ALL OTHER REGISTERS
         MVI   12(13),X'FF'   SET FOOTPRINT IN SAVE AREA
         BR    14             RETURN
*
*
PARM1    DS    F
PARM2    DS    F
PARM3    DS    F
         .
PARMN-1  DS    F
PARMN    DS    F
PARMADDR DC    A(PARM1,PARM2,PARM3,...,PARMN-1)
         DC    X'80',AL3(PARMN)  LEFTMOST BIT ON FOR LAST PARM
RTN$CODE DS    F
SAV$AREA DS    18F
